/**
 * The Worker entry.
 *
 * It exists for one reason: to compile the image codecs while modules are being evaluated.
 * A Worker isolate allows `WebAssembly` compilation at startup and refuses it inside a
 * request handler, and OpenNext loads the Next server bundle with a dynamic import from
 * inside `fetch` — so anything that compiles WASM on first use fails on Cloudflare and
 * succeeds everywhere else, which is the worst way for a difference to show up.
 *
 * These three imports are the same bytes `src/lib/wasm/*.ts` carries as base64 for Node,
 * written by the same generator (`npm run build:wasm`). Wrangler compiles them at deploy
 * time; the request path only instantiates.
 *
 * Everything else is OpenNext's generated worker, re-exported unchanged.
 */
import DEC from "./src/lib/wasm/jpeg-dec.wasm";
import ENC from "./src/lib/wasm/jpeg-enc.wasm";
import RSZ from "./src/lib/wasm/resize.wasm";

(globalThis as { __GALLERY_CODECS__?: unknown }).__GALLERY_CODECS__ = { dec: DEC, enc: ENC, rsz: RSZ };

// @ts-expect-error — generated by `opennextjs-cloudflare build`, not present until then.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
// @ts-expect-error — same generated module.
export { default } from "./.open-next/worker.js";
