// Generate the codec payloads, in the two shapes the two builders will take.
//
// The WASM here is emscripten and wasm-bindgen output: it imports its glue functions from
// modules named `a` and `wbg`, which a bundler tries and fails to resolve as JavaScript.
// Neither Turbopack nor webpack can take these as WebAssembly modules, so the Next build gets
// them as base64 and compiles them itself. That works under Node and does NOT work on
// Cloudflare: a Worker isolate refuses WebAssembly compilation outside module evaluation, and
// the Next server bundle is evaluated inside a request. So the Worker entry gets the same
// bytes as real `.wasm` files, which wrangler compiles at deploy time and workerd hands over
// already compiled.
//
// Same bytes, same codecs, one generator — the two shapes cannot drift apart.
//
// Run: npm run build:wasm
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const CODECS = {
  "jpeg-dec": "@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm",
  "jpeg-enc": "@jsquash/jpeg/codec/enc/mozjpeg_enc.wasm",
  "resize": "@jsquash/resize/lib/resize/pkg/squoosh_resize_bg.wasm",
};

for (const [name, spec] of Object.entries(CODECS)) {
  const bytes = readFileSync(require.resolve(spec));
  const b64 = bytes.toString("base64");
  writeFileSync(`src/lib/wasm/${name}.ts`,
    `// GENERATED by src/lib/wasm/embed.mjs from ${spec}. Do not edit.\n` +
    `// ${(bytes.length / 1024).toFixed(0)} KB of WebAssembly, carried as base64 so no bundler\n` +
    `// needs to understand .wasm — see the generator for why that matters.\n` +
    `export default "${b64}";\n`);
  copyFileSync(require.resolve(spec), `src/lib/wasm/${name}.wasm`);
  console.log(`  src/lib/wasm/${name}.ts  ${(bytes.length / 1024).toFixed(0)} KB -> ${(b64.length / 1024).toFixed(0)} KB base64`);
  console.log(`  src/lib/wasm/${name}.wasm  ${(bytes.length / 1024).toFixed(0)} KB, for the Worker entry`);
}
