// Generate the embedded codec modules.
//
// The WASM here is emscripten and wasm-bindgen output: it imports its glue functions from
// modules named `a` and `wbg`, which a bundler tries and fails to resolve as JavaScript. That
// is why neither Turbopack nor webpack can take these as WebAssembly modules, and why they are
// carried as bytes instead. Base64 costs about a third in source size and buys a codec path
// with no bundler feature behind it, identical in Node and on Workers.
//
// Run: npm run build:wasm
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const CODECS = {
  "jpeg-dec": "@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm",
  "jpeg-enc": "@jsquash/jpeg/codec/enc/mozjpeg_enc.wasm",
  "resize": "@jsquash/resize/lib/resize/pkg/squoosh_resize_bg.wasm",
};

for (const [name, spec] of Object.entries(CODECS)) {
  const bytes = readFileSync(require.resolve(spec));
  const b64 = bytes.toString("base64");
  writeFileSync(`src/lib/wasm/${name}.ts`,
    `// GENERATED by src/lib/wasm/embed.mjs from ${spec}. Do not edit.\n` +
    `// ${(bytes.length / 1024).toFixed(0)} KB of WebAssembly, carried as base64 so no bundler\n` +
    `// needs to understand .wasm — see the generator for why that matters.\n` +
    `export default "${b64}";\n`);
  console.log(`  src/lib/wasm/${name}.ts  ${(bytes.length / 1024).toFixed(0)} KB -> ${(b64.length / 1024).toFixed(0)} KB base64`);
}
