// Flatten the migrations into one file that can be pasted into a hosted SQL editor.
//
// This exists so applying the schema does not require cloning the repository, installing
// Node, or handing a database password to a build environment. The migrations remain the
// source of truth; this is a rendering of them.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA = process.env.GALLERY_SCHEMA ?? "gallery";

const head = `-- The Gallery — complete schema, ready to paste into the Supabase SQL editor.
--
-- GENERATED from db/migrations/*.sql. Do not edit this file; edit the migrations and
-- regenerate with \`npm run db:sqlfile\`.
--
-- There is no password to fill in. Since GAL-SUPA-1 the application connects as an ordinary
-- Supabase client: PostgREST holds the connection and switches into \`anon\` or
-- \`authenticated\`, and this schema decides what each may do.
--
-- Everything below creates objects in the \`${SCHEMA}\` schema only. Nothing is created in
-- \`public\`, so it cannot collide with anything else in this project.
`;

// An argument renders only the migrations from that number on, for a database that already
// carries the earlier ones. `node db/sqlfile.ts 005` writes db/supabase-delta.sql.
const from = process.argv[2];

const deltaHead = `-- The Gallery — migrations from ${from} on, for a database that already carries the earlier
-- ones. GENERATED from db/migrations/*.sql by \`npm run db:sqlfile ${from}\`; do not edit.
--
-- Each migration is idempotent where it can be and states plainly where it is not. Everything
-- below touches the \`${SCHEMA}\` schema only.
`;

const all = readdirSync(join(HERE, "migrations")).filter((n) => n.endsWith(".sql")).sort();
const chosen = from ? all.filter((n) => n >= from) : all;
if (from && chosen.length === 0) throw new Error(`no migration at or after ${from}`);

const parts = [from ? deltaHead : head];
for (const f of chosen) {
  parts.push(`\n-- ============================================================ ${f}\n`);
  parts.push(readFileSync(join(HERE, "migrations", f), "utf8")
    .replaceAll("@schema@", SCHEMA));
}
const out = from ? "supabase-delta.sql" : "supabase-schema.sql";
writeFileSync(join(HERE, out), parts.join(""));
console.log(`db/${out} written (schema: ${SCHEMA}${from ? `, from ${from}` : ""})`);
