// Flatten the migrations into one file that can be pasted into a hosted SQL editor.
//
// This exists so applying the schema does not require cloning the repository, installing
// Node, or handing a database password to a build environment. The migrations remain the
// source of truth; this is a rendering of them.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA = process.env.GALLERY_SCHEMA ?? "gallery";
const PASSWORD = process.env.GALLERY_APP_PASSWORD ?? "CHANGE_ME";

const head = `-- The Gallery — complete schema, ready to paste into the Supabase SQL editor.
--
-- GENERATED from db/migrations/*.sql. Do not edit this file; edit the migrations and
-- regenerate with \`npm run db:sqlfile\`.
--
-- BEFORE YOU RUN IT: replace ${PASSWORD} below with a password you generate. It is the password
-- the application will use to connect at runtime, and it is NOT your database password.
--
-- Everything below creates objects in the \`${SCHEMA}\` schema only. Nothing is created in
-- \`public\`, so it cannot collide with anything else in this project.
`;

const parts = [head];
for (const f of readdirSync(join(HERE, "migrations")).filter((n) => n.endsWith(".sql")).sort()) {
  parts.push(`\n-- ============================================================ ${f}\n`);
  parts.push(readFileSync(join(HERE, "migrations", f), "utf8")
    .replaceAll("@schema@", SCHEMA).replaceAll("@app_password@", PASSWORD));
}
writeFileSync(join(HERE, "supabase-schema.sql"), parts.join(""));
console.log(`db/supabase-schema.sql written (schema: ${SCHEMA})`);
