-- The Gallery — complete schema, ready to paste into the Supabase SQL editor.
--
-- GENERATED from db/migrations/*.sql. Do not edit this file; edit the migrations and
-- regenerate with `npm run db:sqlfile`.
--
-- There is no password to fill in. Since GAL-SUPA-1 the application connects as an ordinary
-- Supabase client: PostgREST holds the connection and switches into `anon` or
-- `authenticated`, and this schema decides what each may do.
--
-- Everything below creates objects in the `gallery` schema only. Nothing is created in
-- `public`, so it cannot collide with anything else in this project.

-- ============================================================ 001_foundation.sql
-- SCHEMA ISOLATION. Every object this product owns lives in ONE schema, and nothing is
-- created in `public`. That is what makes it safe to host The Gallery inside a Supabase
-- project that already carries another product: a name clash is impossible, the whole product
-- dumps and restores as one schema, and a migration run against the wrong database cannot
-- touch tables it does not own.
--
-- The schema name is a plain gallery token substituted by the migration runner (db/cli.ts,
-- GALLERY_SCHEMA, default `gallery`), rather than a psql variable, so the same file runs
-- through psql and through the Node runner without one of them choking on meta-commands.
CREATE SCHEMA IF NOT EXISTS "gallery";
SET search_path = "gallery";

-- The Gallery — Stage 2 substrate, Supabase-native (decision GAL-SUPA-1).
--
-- Authority: product/DOMAIN_MODEL.md (entities, state machines, visibility rules, invariants)
-- and the governor-ratified decisions in doctrine/PRODUCT_STATE.json.
--
-- Identity comes from Supabase Auth. A request arrives at PostgREST carrying a JWT; PostgREST
-- sets the role to `anon` or `authenticated` and puts the claims where `auth.uid()` reads
-- them. This product mints no sessions, stores no password and issues no tokens: GoTrue owns
-- the door. What this schema owns is what happens after the door.
--
-- The permission model is enforced in TWO independent ways, because either alone is a single
-- point of failure:
--   1. GRANTS — `anon` has no grant on any base table at all. A direct anonymous read of
--               `works` fails with "permission denied", not with an empty result that a
--               policy bug could turn into rows.
--   2. RLS    — every base table has row-level security. `authenticated` reaches only its
--               own maker's rows.
--
-- This matters more here than in a single-product project. `auth.users` is per project and
-- this one is shared with another product, so a valid token is not evidence of anything: it
-- may belong to a stranger who has never seen The Gallery. Every policy below is written for
-- that reader (GAL-SUPA-1 accepted consequence 1).

-- ---------------------------------------------------------------- identity of a request
-- auth.uid() is Supabase's own reader of the JWT `sub` claim. It is referenced, never
-- redefined: the day its implementation changes, this product changes with it.

-- Operator authority is a row, not a claim. A JWT claim would have to be minted by something,
-- and that something would then be the real authority; a table is inspectable, revocable and
-- has no issuer.
CREATE TABLE IF NOT EXISTS operators (
  user_id    uuid PRIMARY KEY,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- SECURITY DEFINER so a policy may call it without the caller needing to read `operators`,
-- and so it cannot recurse through the policies on the table it reads.
CREATE OR REPLACE FUNCTION is_operator() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = "gallery" AS $$
  SELECT EXISTS (SELECT 1 FROM operators o WHERE o.user_id = auth.uid())
$$;

-- ---------------------------------------------------------------------------- makers
CREATE TABLE makers (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- One maker per Supabase user. ON DELETE CASCADE so deleting the auth user takes the
  -- product's record of them with it, rather than leaving an orphan nobody can reach.
  user_id              uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  handle               text NOT NULL UNIQUE CHECK (handle ~ '^[a-z0-9]([a-z0-9-]{1,28}[a-z0-9])$'),
  display_name         text NOT NULL CHECK (btrim(display_name) <> ''),
  kind                 text NOT NULL CHECK (kind IN ('individual','studio','collective')),
  city                 text NOT NULL CHECK (btrim(city) <> ''),
  region               text,
  country              text NOT NULL DEFAULT 'India',
  exact_address        text,
  exact_address_public boolean NOT NULL DEFAULT false,
  practice_note        text,
  commissions_open     boolean NOT NULL DEFAULT false,
  commissions_note     text,
  status               text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','closed')),
  status_reason        text,
  handle_locked        boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE galleries (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  maker_id     uuid NOT NULL UNIQUE REFERENCES makers(id) ON DELETE CASCADE,
  lifecycle    text NOT NULL DEFAULT 'draft' CHECK (lifecycle IN ('draft','published','hidden','closed')),
  intro        text,
  published_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE material_categories (
  key      text PRIMARY KEY,
  label    text NOT NULL,
  position int  NOT NULL,
  active   boolean NOT NULL DEFAULT true
);

CREATE TABLE works (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_token        text NOT NULL UNIQUE,
  gallery_id          uuid NOT NULL REFERENCES galleries(id) ON DELETE CASCADE,
  title               text NOT NULL CHECK (btrim(title) <> ''),
  material            text NOT NULL REFERENCES material_categories(key),
  medium              text,
  process             text,
  height_mm           int, width_mm int, depth_mm int,
  year                int,
  price_mode          text NOT NULL CHECK (price_mode IN ('exact','enquire','made_to_order')),
  price_amount        numeric(12,2),
  price_currency      text NOT NULL DEFAULT 'INR',
  status              text NOT NULL DEFAULT 'available'
                      CHECK (status IN ('available','made_to_order','enquire','sold','on_view')),
  status_confirmed_at timestamptz NOT NULL DEFAULT now(),
  lifecycle           text NOT NULL DEFAULT 'draft' CHECK (lifecycle IN ('draft','published','retired')),
  taken_down          boolean NOT NULL DEFAULT false,
  taken_down_reason   text,
  published_at        timestamptz,
  retired_at          timestamptz,
  position            int NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  -- DOMAIN_MODEL §4: price_amount required iff price_mode = 'exact'
  CONSTRAINT works_price_shape CHECK (
    (price_mode = 'exact' AND price_amount IS NOT NULL AND price_amount >= 0)
    OR (price_mode <> 'exact' AND price_amount IS NULL))
);
CREATE INDEX works_gallery_idx ON works (gallery_id);
CREATE INDEX works_material_idx ON works (material);

CREATE TABLE work_images (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  work_id     uuid NOT NULL REFERENCES works(id) ON DELETE CASCADE,
  position    int NOT NULL,
  storage_key text NOT NULL,
  width       int NOT NULL,
  height      int NOT NULL,
  alt_text    text,
  state       text NOT NULL DEFAULT 'uploading' CHECK (state IN ('uploading','ready','failed')),
  variants    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX work_images_position_key ON work_images (work_id, position);

CREATE TABLE contact_routes (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  maker_id   uuid NOT NULL REFERENCES makers(id) ON DELETE CASCADE,
  kind       text NOT NULL CHECK (kind IN ('whatsapp','email','phone','website','form')),
  value      text NOT NULL CHECK (btrim(value) <> ''),
  label      text,
  enabled    boolean NOT NULL DEFAULT true,
  validated  boolean NOT NULL DEFAULT false,
  position   int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_routes_maker_idx ON contact_routes (maker_id);

-- Append-only. No UPDATE or DELETE grant is issued to any role, and the triggers below refuse
-- them even for the owner: a sanction never rewrites its own record.
--
-- actor_user_id carries no foreign key on purpose. A record of a sanction must outlive the
-- account that issued it; a cascade or a restrict would let deleting an operator either erase
-- the record or block the deletion.
CREATE TABLE operator_actions (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_user_id        uuid NOT NULL,
  action               text NOT NULL CHECK (action IN
                         ('take_down','restore','suspend','reinstate','dismiss_report','close_report','vocabulary_change')),
  subject_type         text NOT NULL CHECK (subject_type IN ('work','maker','workshop','collection','report')),
  subject_id           uuid NOT NULL,
  reason               text NOT NULL CHECK (btrim(reason) <> ''),
  supersedes_action_id uuid REFERENCES operator_actions(id),
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX operator_actions_subject_idx ON operator_actions (subject_type, subject_id, created_at DESC);

CREATE OR REPLACE FUNCTION refuse_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'operator_actions is append-only (DOMAIN_MODEL §6)';
END $$;
CREATE TRIGGER operator_actions_no_update BEFORE UPDATE ON operator_actions
  FOR EACH ROW EXECUTE FUNCTION refuse_mutation();
CREATE TRIGGER operator_actions_no_delete BEFORE DELETE ON operator_actions
  FOR EACH ROW EXECUTE FUNCTION refuse_mutation();

-- Idempotency for consequential writes (publish, and any later one-shot act).
CREATE TABLE write_intents (
  key        text PRIMARY KEY,
  user_id    uuid NOT NULL,
  kind       text NOT NULL,
  subject_id uuid,
  result     jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Closure is the product's own record, kept separately from the auth user. Deleting a person
-- from GoTrue is an administrative act with its own key; closing an account is a thing the
-- maker themselves does, and it must be recorded even when no maker profile was ever made.
CREATE TABLE account_closures (
  user_id   uuid PRIMARY KEY,
  closed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE operational_failures (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind        text NOT NULL CHECK (kind IN ('auth','publish','image','contact','email')),
  subject     text NOT NULL,
  detail      text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

-- ---------------------------------------------------- the maker behind the current request
-- SECURITY DEFINER so it can be used inside policies on `makers` itself without recursing
-- through those policies.
CREATE OR REPLACE FUNCTION maker_id() RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = "gallery" AS $$
  SELECT m.id FROM makers m WHERE m.user_id = auth.uid()
$$;

-- The maker behind the current request ONLY while they may act.
--
-- GAL-A1: "a suspended maker cannot publish or exercise maker privileges." Enforcing that in
-- the application would satisfy the letter of it; enforcing it here means a suspended maker
-- writing directly to the API — which the exposed schema now makes possible — is refused by
-- the database rather than by a page they are not using. Reads still go through maker_id(),
-- because a suspended maker must be able to see their own Studio and read why.
CREATE OR REPLACE FUNCTION writing_maker_id() RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = "gallery" AS $$
  SELECT m.id FROM makers m WHERE m.user_id = auth.uid() AND m.status = 'active'
$$;

-- ============================================================ 002_visibility_and_policies.sql
CREATE SCHEMA IF NOT EXISTS "gallery";
SET search_path = "gallery";

-- The Gallery — public views, grants, row-level security, transition functions.
--
-- DOMAIN_MODEL §3: "An object is public only when every ancestor is public: work published
-- AND gallery published AND maker active." That predicate lives in ONE place — the views
-- below — and every public surface reads them. Discovery, search, work detail, maker gallery
-- and the image route all go through the same predicate, so a surface cannot drift.

-- ------------------------------------------------------------------ the public predicate
--
-- These views are deliberately NOT security_invoker. They run with the owner's rights, which
-- is exactly why `anon` can be granted the view and nothing underneath it: the visibility
-- predicate is the only way through. Supabase's linter flags owner-rights views in an exposed
-- schema, and here that shape is the control, not an oversight.
CREATE OR REPLACE VIEW public_makers AS
SELECT m.id, m.handle, m.display_name, m.kind, m.city, m.region, m.country,
       CASE WHEN m.exact_address_public THEN m.exact_address END AS exact_address,
       m.practice_note, m.commissions_open, m.commissions_note,
       g.id AS gallery_id, g.intro AS gallery_intro, g.published_at AS gallery_published_at
FROM makers m
JOIN galleries g ON g.maker_id = m.id
WHERE m.status = 'active' AND g.lifecycle = 'published';
-- Deliberately absent: user_id, status_reason, exact_address when private, and anything at
-- all from auth.users. The account email has no path to a public surface.

CREATE OR REPLACE VIEW public_works AS
SELECT w.id, w.public_token, w.title, w.material, w.medium, w.process,
       w.height_mm, w.width_mm, w.depth_mm, w.year,
       w.price_mode, w.price_amount, w.price_currency,
       w.status, w.status_confirmed_at, w.published_at, w.position,
       pm.id AS maker_id, pm.handle AS maker_handle, pm.display_name AS maker_display_name,
       pm.city AS maker_city, pm.kind AS maker_kind
FROM works w
JOIN galleries g      ON g.id = w.gallery_id
JOIN public_makers pm ON pm.gallery_id = g.id
WHERE w.lifecycle = 'published' AND w.taken_down = false;

-- A retired or taken-down work keeps its URL and renders a truthful ending
-- (PRODUCT_ARCHITECTURE §4.1). This view carries only what that ending needs.
CREATE OR REPLACE VIEW public_work_endings AS
SELECT w.public_token, w.title, w.lifecycle, w.taken_down,
       m.handle AS maker_handle, m.display_name AS maker_display_name, m.status AS maker_status
FROM works w
JOIN galleries g ON g.id = w.gallery_id
JOIN makers m    ON m.id = g.maker_id;

CREATE OR REPLACE VIEW public_work_images AS
SELECT i.id, i.work_id, i.position, i.width, i.height, i.alt_text, i.variants
FROM work_images i
JOIN public_works pw ON pw.id = i.work_id
WHERE i.state = 'ready';

-- A route becomes an action only when enabled AND validated (DOMAIN_MODEL §2.7).
CREATE OR REPLACE VIEW public_contact_routes AS
SELECT r.id, r.maker_id, r.kind, r.value, r.label, r.position
FROM contact_routes r
JOIN public_makers pm ON pm.id = r.maker_id
WHERE r.enabled = true AND r.validated = true;

-- ---------------------------------------------------------------------------- grants
-- `anon` gets NOTHING on any base table. Not a policy that returns zero rows — no grant at
-- all, so a direct read raises "permission denied for table works".
GRANT USAGE ON SCHEMA "gallery" TO anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA "gallery" FROM anon, authenticated;

GRANT SELECT ON public_makers, public_works, public_work_images, public_contact_routes,
                public_work_endings, material_categories TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON makers, galleries, works, work_images, contact_routes TO authenticated;
GRANT DELETE ON work_images, contact_routes TO authenticated;
GRANT SELECT, INSERT ON operator_actions TO authenticated;
GRANT SELECT, INSERT ON write_intents TO authenticated;
GRANT SELECT ON account_closures TO authenticated;
GRANT INSERT ON operational_failures TO authenticated;
-- `operators` is granted to nobody. It is read only through is_operator(), which is SECURITY
-- DEFINER, so no client can enumerate who holds operator authority.

-- ------------------------------------------------------------------ row-level security
ALTER TABLE makers               ENABLE ROW LEVEL SECURITY;
ALTER TABLE galleries            ENABLE ROW LEVEL SECURITY;
ALTER TABLE works                ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_images          ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_routes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE operator_actions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE write_intents        ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_closures     ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE operators            ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_categories  ENABLE ROW LEVEL SECURITY;
-- material_categories is the browse vocabulary and carries no private data, so it is readable
-- by everyone. RLS is on with an explicit permissive policy rather than off, so that "RLS is
-- enabled on every table in this schema" stays a property that can be checked mechanically.
CREATE POLICY vocabulary_readable ON material_categories FOR SELECT TO anon, authenticated
  USING (true);

-- `operators` has RLS enabled and NO policy at all: that is a table nobody may read through
-- the API, by construction rather than by omission.

CREATE POLICY maker_self ON makers FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR is_operator());
CREATE POLICY maker_self_insert ON makers FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY maker_self_update ON makers FOR UPDATE TO authenticated
  USING (user_id = auth.uid() AND status = 'active')
  WITH CHECK (user_id = auth.uid() AND status = 'active');

CREATE POLICY gallery_self ON galleries FOR SELECT TO authenticated
  USING (maker_id = maker_id() OR is_operator());
CREATE POLICY gallery_self_insert ON galleries FOR INSERT TO authenticated
  WITH CHECK (maker_id = writing_maker_id());
CREATE POLICY gallery_self_update ON galleries FOR UPDATE TO authenticated
  USING (maker_id = writing_maker_id()) WITH CHECK (maker_id = writing_maker_id());

CREATE POLICY work_self ON works FOR SELECT TO authenticated
  USING (gallery_id IN (SELECT id FROM galleries WHERE maker_id = maker_id()) OR is_operator());
CREATE POLICY work_self_insert ON works FOR INSERT TO authenticated
  WITH CHECK (gallery_id IN (SELECT id FROM galleries WHERE maker_id = writing_maker_id()));
CREATE POLICY work_self_update ON works FOR UPDATE TO authenticated
  USING (gallery_id IN (SELECT id FROM galleries WHERE maker_id = writing_maker_id()))
  WITH CHECK (gallery_id IN (SELECT id FROM galleries WHERE maker_id = writing_maker_id()));

CREATE POLICY image_self_read ON work_images FOR SELECT TO authenticated
  USING (work_id IN (SELECT w.id FROM works w JOIN galleries g ON g.id = w.gallery_id
                     WHERE g.maker_id = maker_id()));
CREATE POLICY image_self_write ON work_images FOR ALL TO authenticated
  USING (work_id IN (SELECT w.id FROM works w JOIN galleries g ON g.id = w.gallery_id
                     WHERE g.maker_id = writing_maker_id()))
  WITH CHECK (work_id IN (SELECT w.id FROM works w JOIN galleries g ON g.id = w.gallery_id
                     WHERE g.maker_id = writing_maker_id()));

CREATE POLICY route_self_read ON contact_routes FOR SELECT TO authenticated
  USING (maker_id = maker_id());
CREATE POLICY route_self_write ON contact_routes FOR ALL TO authenticated
  USING (maker_id = writing_maker_id()) WITH CHECK (maker_id = writing_maker_id());

CREATE POLICY intent_self ON write_intents FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY closure_self ON account_closures FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY failure_insert ON operational_failures FOR INSERT TO authenticated WITH CHECK (true);

-- Only an operator may write the append-only record, and only as themselves.
CREATE POLICY operator_read ON operator_actions FOR SELECT TO authenticated
  USING (is_operator());
CREATE POLICY operator_write ON operator_actions FOR INSERT TO authenticated
  WITH CHECK (is_operator() AND actor_user_id = auth.uid());

-- ------------------------------------------------------------------ transition functions
-- Every consequential state change re-reads its row under a lock and predicates the write on
-- the current state (DOMAIN_MODEL §4), so a double submit or a retry cannot half-apply.
--
-- SECURITY INVOKER where the caller's own rights are the authority: the policies above decide
-- whether the row is theirs, and the function adds the ordering and the locking. A caller who
-- does not own the work sees "not found", because the policy hid it before the function ran.

CREATE OR REPLACE FUNCTION publish_work(p_work_id uuid, p_intent_key text)
RETURNS TABLE (outcome text, work_id uuid, public_token text)
LANGUAGE plpgsql SECURITY INVOKER SET search_path = "gallery" AS $$
DECLARE w works%ROWTYPE; g galleries%ROWTYPE; ready int; existing write_intents%ROWTYPE;
BEGIN
  SELECT * INTO existing FROM write_intents WHERE key = p_intent_key;
  IF FOUND THEN
    -- The same intent replayed: report the first outcome, do not publish twice.
    RETURN QUERY SELECT 'already_applied'::text, existing.subject_id,
                        (SELECT wk.public_token FROM works wk WHERE wk.id = existing.subject_id);
    RETURN;
  END IF;

  SELECT * INTO w FROM works WHERE id = p_work_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'work not found or not yours' USING ERRCODE = '42501'; END IF;
  SELECT * INTO g FROM galleries WHERE id = w.gallery_id FOR UPDATE;

  SELECT count(*) INTO ready FROM work_images WHERE work_images.work_id = p_work_id AND state = 'ready';
  IF ready = 0 THEN RAISE EXCEPTION 'a work publishes only with at least one ready image'; END IF;

  IF w.lifecycle = 'published' THEN
    INSERT INTO write_intents (key, user_id, kind, subject_id, result)
      VALUES (p_intent_key, auth.uid(), 'publish_work', p_work_id, '{"outcome":"already_published"}');
    RETURN QUERY SELECT 'already_published'::text, w.id, w.public_token; RETURN;
  END IF;

  UPDATE works SET lifecycle = 'published', published_at = now(), retired_at = NULL, updated_at = now()
    WHERE id = p_work_id;
  IF g.lifecycle = 'draft' THEN
    UPDATE galleries SET lifecycle = 'published', published_at = now() WHERE id = g.id;
  END IF;
  INSERT INTO write_intents (key, user_id, kind, subject_id, result)
    VALUES (p_intent_key, auth.uid(), 'publish_work', p_work_id, '{"outcome":"published"}');
  RETURN QUERY SELECT 'published'::text, w.id, w.public_token;
END $$;

CREATE OR REPLACE FUNCTION set_work_status(p_work_id uuid, p_status text)
RETURNS text LANGUAGE plpgsql SECURITY INVOKER SET search_path = "gallery" AS $$
DECLARE w works%ROWTYPE;
BEGIN
  SELECT * INTO w FROM works WHERE id = p_work_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'work not found or not yours' USING ERRCODE = '42501'; END IF;
  IF w.lifecycle = 'draft' THEN RAISE EXCEPTION 'status belongs to a work that has been published'; END IF;
  UPDATE works SET status = p_status, status_confirmed_at = now(), updated_at = now() WHERE id = p_work_id;
  RETURN p_status;
END $$;

CREATE OR REPLACE FUNCTION retire_work(p_work_id uuid)
RETURNS text LANGUAGE plpgsql SECURITY INVOKER SET search_path = "gallery" AS $$
BEGIN
  UPDATE works SET lifecycle = 'retired', retired_at = now(), updated_at = now()
    WHERE id = p_work_id AND lifecycle = 'published';
  IF NOT FOUND THEN RAISE EXCEPTION 'work not found, not yours, or not published' USING ERRCODE = '42501'; END IF;
  RETURN 'retired';
END $$;

-- Operator acts. SECURITY DEFINER because the operator legitimately writes another maker's
-- governed state; the first statement is the authority check, so the definer right cannot be
-- borrowed by a maker.
CREATE OR REPLACE FUNCTION set_maker_access(p_maker_id uuid, p_action text, p_reason text)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = "gallery" AS $$
DECLARE m makers%ROWTYPE; new_status text;
BEGIN
  IF NOT is_operator() THEN
    RAISE EXCEPTION 'operator authority required' USING ERRCODE = '42501';
  END IF;
  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'every sanction carries a recorded reason (GAL-OD-15)';
  END IF;
  IF p_action NOT IN ('suspend','reinstate') THEN RAISE EXCEPTION 'unknown action %', p_action; END IF;

  SELECT * INTO m FROM makers WHERE id = p_maker_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'maker not found'; END IF;
  new_status := CASE WHEN p_action = 'suspend' THEN 'suspended' ELSE 'active' END;
  IF m.status = new_status THEN RETURN 'unchanged'; END IF;

  UPDATE makers SET status = new_status,
                    status_reason = CASE WHEN p_action = 'suspend' THEN p_reason ELSE NULL END,
                    updated_at = now()
    WHERE id = p_maker_id;
  INSERT INTO operator_actions (actor_user_id, action, subject_type, subject_id, reason)
    VALUES (auth.uid(), p_action, 'maker', p_maker_id, p_reason);
  RETURN new_status;
END $$;

CREATE OR REPLACE FUNCTION close_account()
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = "gallery" AS $$
DECLARE uid uuid := auth.uid(); mk uuid;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'not signed in' USING ERRCODE = '42501'; END IF;
  SELECT id INTO mk FROM makers WHERE user_id = uid;
  IF mk IS NOT NULL THEN
    IF (SELECT status FROM makers WHERE id = mk) = 'suspended' THEN
      RAISE EXCEPTION 'a suspended account is not closed by the maker (DOMAIN_MODEL §2.1)';
    END IF;
    UPDATE works SET lifecycle = 'retired', retired_at = now(), updated_at = now()
      WHERE gallery_id IN (SELECT id FROM galleries WHERE maker_id = mk) AND lifecycle = 'published';
    UPDATE galleries SET lifecycle = 'closed' WHERE maker_id = mk;
    UPDATE makers SET status = 'closed', updated_at = now() WHERE id = mk;
  END IF;
  INSERT INTO account_closures (user_id) VALUES (uid) ON CONFLICT (user_id) DO NOTHING;
  RETURN 'closed';
END $$;

-- Resolving a published image's stored bytes without handing anyone the storage layout.
--
-- /img/[id]/[variant] needs `storage_key`, which the public view deliberately does not carry:
-- it is internal structure, not something a visitor should be handed. This returns it ONLY for
-- an image that is already publicly visible, reusing public_work_images rather than restating
-- the predicate. A maker's own draft images are not reachable through it; that path goes
-- through the maker's own token, where row-level security scopes it to their work.
CREATE OR REPLACE FUNCTION storage_key_for_public_image(p_image_id uuid)
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = "gallery" AS $$
  SELECT i.storage_key
    FROM work_images i
    JOIN public_work_images p ON p.id = i.id
   WHERE i.id = p_image_id
$$;

-- PostgREST will only expose a function the caller may execute. Default EXECUTE on a new
-- function is PUBLIC, so it is revoked first and then granted deliberately: an RPC that
-- nobody thought about is an open door.
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA "gallery" FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION storage_key_for_public_image(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION is_operator() TO authenticated;
GRANT EXECUTE ON FUNCTION maker_id() TO authenticated;
GRANT EXECUTE ON FUNCTION writing_maker_id() TO authenticated;
GRANT EXECUTE ON FUNCTION publish_work(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION set_work_status(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION retire_work(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION set_maker_access(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION close_account() TO authenticated;

-- ============================================================ 003_seed_and_verify.sql
CREATE SCHEMA IF NOT EXISTS "gallery";
SET search_path = "gallery";

-- Seeded vocabulary (DOMAIN_MODEL §1: clay, textile, wood, metal, paper) and executing
-- VERIFY blocks. A migration that cannot prove its own effect is a hope, not a migration.

INSERT INTO material_categories (key, label, position, active) VALUES
  ('clay',    'Clay',    1, true),
  ('textile', 'Textile', 2, true),
  ('wood',    'Wood',    3, true),
  ('metal',   'Metal',   4, true),
  ('paper',   'Paper',   5, true)
ON CONFLICT (key) DO NOTHING;

DO $verify$
DECLARE n int; leaked text;
BEGIN
  -- V1 the vocabulary is seeded
  SELECT count(*) INTO n FROM material_categories WHERE active;
  IF n <> 5 THEN RAISE EXCEPTION 'VERIFY V1 failed: % active material categories, expected 5', n; END IF;

  -- V2 the anonymous role holds no grant on any base table
  SELECT string_agg(table_name, ', ') INTO leaked
  FROM information_schema.role_table_grants
  WHERE grantee = 'anon'
    AND table_schema = current_schema()
    AND table_name IN ('makers','galleries','works','work_images','contact_routes',
                       'operator_actions','write_intents','operators','account_closures');
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V2 failed: anon holds grants on base tables: %', leaked;
  END IF;

  -- V3 no public view exposes an identity column
  SELECT string_agg(table_name || '.' || column_name, ', ') INTO leaked
  FROM information_schema.columns
  WHERE table_schema = current_schema() AND table_name LIKE 'public\_%'
    AND (column_name ILIKE '%email%' OR column_name ILIKE '%user_id%' OR column_name ILIKE '%password%');
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V3 failed: a public view exposes private identity columns: %', leaked;
  END IF;

  -- V4 every table in the schema has row-level security enabled. Not a named list: in an
  -- exposed schema a table without RLS is reachable by anyone with the publishable key, so
  -- the check must catch a table nobody remembered to add to a list.
  SELECT string_agg(relname, ', ') INTO leaked
  FROM pg_class c JOIN pg_namespace ns ON ns.oid = c.relnamespace
  WHERE ns.nspname = current_schema() AND c.relkind = 'r' AND c.relrowsecurity = false;
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V4 failed: row-level security is off for: %', leaked;
  END IF;

  -- V5 operator_actions carries no UPDATE or DELETE grant for any application role
  SELECT string_agg(grantee || ':' || privilege_type, ', ') INTO leaked
  FROM information_schema.role_table_grants
  WHERE table_schema = current_schema()
    AND table_name = 'operator_actions' AND privilege_type IN ('UPDATE','DELETE')
    AND grantee IN ('anon','authenticated');
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V5 failed: operator_actions is not append-only: %', leaked;
  END IF;

  -- V6 no commerce table reached the schema (GAL-04, refusals GAL-R*)
  SELECT string_agg(table_name, ', ') INTO leaked
  FROM information_schema.tables
  WHERE table_schema = current_schema()
    AND table_name ~ '(cart|checkout|order|payment|wallet|escrow|refund|shipping|dispute)';
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V6 failed: transaction tables present: %', leaked;
  END IF;

  -- V7 no engagement-count column reached the schema (GAL-OD-09)
  SELECT string_agg(table_name || '.' || column_name, ', ') INTO leaked
  FROM information_schema.columns
  WHERE table_schema = current_schema()
    AND column_name ~ '(like_count|likes|follower|following|reaction|comment_count|view_count|popularity|rank_score)';
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V7 failed: engagement columns present: %', leaked;
  END IF;

  -- V8 nobody may execute a function that was never granted deliberately. PostgREST turns
  -- every executable function in an exposed schema into a callable endpoint, so a default
  -- EXECUTE to PUBLIC is an open door rather than an untidiness.
  SELECT string_agg(p.proname, ', ') INTO leaked
  FROM pg_proc p JOIN pg_namespace ns ON ns.oid = p.pronamespace
  WHERE ns.nspname = current_schema()
    AND has_function_privilege('anon', p.oid, 'EXECUTE')
    AND p.proname NOT IN ('storage_key_for_public_image');
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V8 failed: anon can execute functions it was not granted: %', leaked;
  END IF;

  -- V9 the operator table is reachable by nobody through the API: RLS on, no policy, no grant.
  SELECT string_agg(x, ', ') INTO leaked FROM (
    SELECT 'policy ' || polname AS x FROM pg_policy
     WHERE polrelid = (current_schema() || '.operators')::regclass
    UNION ALL
    SELECT 'grant ' || grantee FROM information_schema.role_table_grants
     WHERE table_schema = current_schema() AND table_name = 'operators'
       AND grantee IN ('anon','authenticated')
  ) y;
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V9 failed: operators is reachable: %', leaked;
  END IF;

  -- V10 a suspended maker cannot write. Established from the policy text rather than by
  -- running as a suspended maker, which the probe suite does over HTTP: every write policy
  -- must go through writing_maker_id(), which returns NULL unless the maker is active.
  SELECT string_agg(polname, ', ') INTO leaked
  FROM pg_policy
  WHERE polrelid IN ((current_schema() || '.works')::regclass,
                     (current_schema() || '.work_images')::regclass,
                     (current_schema() || '.contact_routes')::regclass,
                     (current_schema() || '.galleries')::regclass)
    AND polcmd <> 'r'
    AND pg_get_expr(polwithcheck, polrelid) NOT LIKE '%writing_maker_id%';
  IF leaked IS NOT NULL THEN
    RAISE EXCEPTION 'VERIFY V10 failed: write policies that do not check maker status: %', leaked;
  END IF;

  RAISE NOTICE 'VERIFY V1-V10 passed';
END $verify$;
